export { default as Header } from './Header';
export { default as Hero } from './Hero';
export { default as WhatWeOffer } from './WhatWeOffer';
export { default as OurExpertise } from './OurExpertise';
export { default as Services } from './Services';
export { default as Sectors } from './Sectors';
export { default as Specialists } from './Specialists';
export { default as CTASection } from './CTASection';
export { default as Footer } from './Footer';
